name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 3.0.1
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^2.1.0
  collection: ^1.15.0
